"""Interfaces de repositório para IncomeSource, FinancialObligation e Debt."""

from __future__ import annotations

from typing import Optional, Protocol

from src.domain.obligations.entities import Debt, FinancialObligation, IncomeSource


class IncomeSourceRepository(Protocol):
    def add(self, income: IncomeSource) -> None: ...
    def get(self, income_id: str) -> Optional[IncomeSource]: ...
    def list_by_profile(self, profile_id: str) -> list[IncomeSource]: ...
    def update(self, income: IncomeSource) -> None: ...
    def delete(self, income_id: str) -> None: ...


class ObligationRepository(Protocol):
    def add(self, obligation: FinancialObligation) -> None: ...
    def get(self, obligation_id: str) -> Optional[FinancialObligation]: ...
    def list_by_profile(self, profile_id: str) -> list[FinancialObligation]: ...
    def update(self, obligation: FinancialObligation) -> None: ...
    def delete(self, obligation_id: str) -> None: ...


class DebtRepository(Protocol):
    def add(self, debt: Debt) -> None: ...
    def get(self, debt_id: str) -> Optional[Debt]: ...
    def list_by_profile(self, profile_id: str) -> list[Debt]: ...
    def update(self, debt: Debt) -> None: ...
    def delete(self, debt_id: str) -> None: ...
