"""Interfaces de repositório para FinancialGoal e Simulation (agregado decisions)."""

from __future__ import annotations

from typing import Optional, Protocol

from src.domain.decisions.entities import FinancialGoal, Simulation


class GoalRepository(Protocol):
    def add(self, goal: FinancialGoal) -> None: ...
    def get(self, goal_id: str) -> Optional[FinancialGoal]: ...
    def list_by_profile(self, profile_id: str) -> list[FinancialGoal]: ...
    def update(self, goal: FinancialGoal) -> None: ...
    def delete(self, goal_id: str) -> None: ...


class SimulationRepository(Protocol):
    def add(self, simulation: Simulation) -> None: ...
    def get(self, simulation_id: str) -> Optional[Simulation]: ...
    def list_by_profile(self, profile_id: str) -> list[Simulation]: ...
    def delete(self, simulation_id: str) -> None: ...
