"""initial schema

Revision ID: 0566f42ed6b2
Revises: 
Create Date: 2026-07-23 09:23:04.960152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0566f42ed6b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('dependents', sa.Integer(), nullable=False),
    sa.Column('monthly_expense_reduction_capacity', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('balance_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('balance_currency', sa.String(length=3), nullable=False),
    sa.Column('liquidity_type', sa.Enum('CHECKING_ACCOUNT', 'SAVINGS_ACCOUNT', 'EMERGENCY_FUND', 'INVESTMENT', 'OTHER', name='liquiditytype'), nullable=False),
    sa.Column('eligible_for_autonomy', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('outstanding_balance_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('outstanding_balance_currency', sa.String(length=3), nullable=False),
    sa.Column('installment_amount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('installment_amount_currency', sa.String(length=3), nullable=False),
    sa.Column('remaining_installments', sa.Integer(), nullable=False),
    sa.Column('interest_rate_optional', sa.String(length=20), nullable=True),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('amount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount_currency', sa.String(length=3), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('recurrence', sa.Enum('ONE_OFF', 'MONTHLY', 'WEEKLY', 'YEARLY', name='recurrence'), nullable=True),
    sa.Column('direction', sa.Enum('INCOME', 'EXPENSE', name='direction'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_goals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('target_amount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('target_amount_currency', sa.String(length=3), nullable=False),
    sa.Column('current_amount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('current_amount_currency', sa.String(length=3), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('monthly_contribution_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monthly_contribution_currency', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('income_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount_currency', sa.String(length=3), nullable=False),
    sa.Column('frequency', sa.Enum('ONE_OFF', 'MONTHLY', 'WEEKLY', 'YEARLY', name='recurrence'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('stability', sa.Enum('STABLE', 'VARIABLE', name='incomestability'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obligations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount_currency', sa.String(length=3), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.Enum('ONE_OFF', 'MONTHLY', 'WEEKLY', 'YEARLY', name='recurrence'), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('essential', sa.Boolean(), nullable=False),
    sa.Column('debt_related', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('obligations')
    op.drop_table('income_sources')
    op.drop_table('financial_goals')
    op.drop_table('financial_events')
    op.drop_table('debts')
    op.drop_table('accounts')
    op.drop_table('profiles')
    # ### end Alembic commands ###
