"""balance_snapshots

Revision ID: 59331c899349
Revises: f1b2c3d4e5a6
Create Date: 2026-07-28 14:31:18.127294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59331c899349'
down_revision: Union[str, None] = 'f1b2c3d4e5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('net_balance_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_balance_currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'period', name='uq_balance_snapshots_profile_period')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('balance_snapshots')
    # ### end Alembic commands ###
