"""preventive_plans

Revision ID: cc81d6a213fa
Revises: 0a457ffa0a4d
Create Date: 2026-07-24 17:01:12.644045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc81d6a213fa'
down_revision: Union[str, None] = '0a457ffa0a4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preventive_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('risk_code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'APPROVED', 'REJECTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='planstatus'), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('expected_result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preventive_plans')
    # ### end Alembic commands ###
